# Generated by Django 6.1.1 on 2026-09-30 17:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0001_initial'),
        ('usuarios', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='grupo',
            name='estudiantes',
            field=models.ManyToManyField(blank=True, limit_choices_to={'rol': 'ESTUDIANTE'}, related_name='grupos', to='usuarios.perfil'),
        ),
    ]
